# Generated by Django 5.0 on 2026-09-17 16:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64, unique=True, validators=[django.core.validators.MinLengthValidator(3)])),
                ('email', models.EmailField(max_length=256)),
                ('password', models.CharField(max_length=256)),
                ('first_name', models.CharField(max_length=64, validators=[django.core.validators.MinLengthValidator(3)])),
                ('last_name', models.CharField(max_length=64, validators=[django.core.validators.MinLengthValidator(3)])),
                ('bio', models.TextField(default='')),
                ('birth_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
