# Generated by Django 5.0 on 2026-09-19 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(blank=True, choices=[('low', 'Past'), ('middle', "O'rta"), ('high', 'Yuqori')], default='middle', max_length=20),
        ),
    ]
